{
   "name":"azure_onnx",
   "platform":"onnxruntime_onnx",
   "backend":"onnxruntime",
   "version_policy":{
      "latest":{
         "num_versions":1
      }
   },
   "max_batch_size":0,
   "input":[
      {
         "name":"input",
         "data_type":"TYPE_FP32",
         "format":"FORMAT_NONE",
         "dims":[
            -1,
            3,
            640,
            640
         ],
         "is_shape_tensor":false,
         "allow_ragged_batch":false
      }
   ],
   "output":[
      {
         "name":"1702",
         "data_type":"TYPE_FP32",
         "dims":[
            1,
            3,
            20,
            20,
            8
         ],
         "label_filename":"",
         "is_shape_tensor":false
      },
      {
         "name":"1354",
         "data_type":"TYPE_FP32",
         "dims":[
            1,
            3,
            40,
            40,
            8
         ],
         "label_filename":"",
         "is_shape_tensor":false
      },
      {
         "name":"output",
         "data_type":"TYPE_FP32",
         "dims":[
            -1,
            25200,
            8
         ],
         "label_filename":"labels.txt",
         "is_shape_tensor":false
      },
      {
         "name":"1006",
         "data_type":"TYPE_FP32",
         "dims":[
            1,
            3,
            80,
            80,
            8
         ],
         "label_filename":"",
         "is_shape_tensor":false
      }
   ],
   "batch_input":[
      
   ],
   "batch_output":[
      
   ],
   "optimization":{
      "priority":"PRIORITY_DEFAULT",
      "input_pinned_memory":{
         "enable":true
      },
      "output_pinned_memory":{
         "enable":true
      }
   },
   "instance_group":[
      {
         "name":"azure_onnx",
         "kind":"KIND_CPU",
         "count":1,
         "gpus":[
            
         ],
         "profile":[
            
         ]
      }
   ],
   "default_model_filename":"model.onnx",
   "cc_model_filenames":{
      
   },
   "metric_tags":{
      
   },
   "parameters":{
      
   },
   "model_warmup":[
      
   ]
}